export enum AppRoutes {
  HOME = "/",
  LOGIN = "/login",
  TEAM = "/team",
  TEAM_PORTAL_ADD = "/portal/team/add",
  TEAM_PORTAL_EDIT = "/portal/team/edit",
  TEAMS = "/teams",
  ACCOUNT = "/portal/settings/account",
  SIGNUP = "/portal/signup",
  FEEDBACK = "/portal/feedback",
  FEEDBACKTHANKYOU = "/feedback-thank-you",
  SCOUTING = "/portal/scouting",
  SCOUTING_NEW = "/portal/scouting/new",
  SCOUTING_EVENT = "/portal/scouting/event",
  SCOUTING_EDIT = "/portal/scouting/edit",
  SCOUTING_SCHEDULE = "/portal/scouting/schedule",
}
