name: Build and Deploy JustScout

on:
  push:
    branches: [main, restart]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout the Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Write .env File from GitHub Secret
      - name: Create .env File
        run: |
          echo "${{ secrets.ENV_VARS }}" > .env

      # Step 3: Build the Docker Image
      - name: Build Docker Image
        run: docker build -t justscout .

      # Step 4: Stop and Remove Existing Container (Robust Cleanup)
      - name: Stop and Remove Existing Container
        run: |
          if [ "$(docker ps -aq -f name=justscout-container)" ]; then
            docker stop justscout-container || true
            docker rm justscout-container || true
          fi

      # Step 5: Run New Container with Correct Port Mapping
      - name: Run New Container with Health Check
        run: |
          docker run -d \
            -p 5000:3000 \ # Map host's port 5000 to container's port 3000
            --name justscout-container \
            --restart unless-stopped \
            --health-cmd="curl -f http://localhost:5000/ || exit 1" \
            --health-interval=30s \
            --health-timeout=10s \
            --health-retries=3 \
            justscout

      # Step 6: Clean Up Old Docker Images
      - name: Remove Unused Docker Images
        run: docker image prune -f
